name: karmm_callkit
description: A Flutter plugin for displaying call screen when app in background or terminated.
version: 0.0.10
homepage: https://gtsinfosoft.com/
issue_tracker: https://github.com/kapilsharma-gts/karmm_callkit/issues
documentation: https://github.com/kapilsharma-gts/karmm_callkit/blob/master/README.md
repository: https://github.com/kapilsharma-gts/karmm_callkit

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

  universal_io: ^2.0.4
  fluttertoast: ^8.2.5
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^17.1.2
  receive_intent: ^0.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.karmm.callkit
        pluginClass: ConnectycubeFlutterCallKitPlugin
      ios:
        pluginClass: ConnectycubeFlutterCallKitPlugin